"""
Locators related to homepage page
"""


profile_button = "//span[@class='myntraweb-sprite desktop-iconUser sprites-headerUser']"
signup_button = "//*[@class='desktop-linkButton']"
mobile_number = "//*[@class='form-control mobileNumberInput']"
continue_button = "//*[@class='submitBottomOption']"
log_in_using_password = "//span[normalize-space()='Password']"
password = "//input[@type='password']"
otp_field_1 = "//input[@name='otp0']"
otp_field_2 = "//input[@name='otp1']"
otp_field_3 = "//input[@name='otp2']"
otp_field_4 = "//input[@name='otp3']"
final_login_button = "//button[normalize-space()='LOGIN']"
logout_button = "//div[contains(text(),'Logout')]"
login_button = "//a[@class='desktop-linkButton']"
contact_us = "//div[contains(text(),'Contact')]"
faq = "//div[contains(text(),'Frequently Asked Questions')]"
faq_text = "//div[@class='faqspage-header']"
help_center_text = "//div[contains(text(),'HELP CENTER')]"
homepage_verification_text = "//strong[normalize-space()='100% ORIGINAL']"
wishlist_button = "//span[@class='myntraweb-sprite desktop-iconWishlist sprites-headerWishlist']"
bag_buuton = "//span[@class='myntraweb-sprite desktop-iconBag sprites-headerBag']"
cart_button = "//span[@class='myntraweb-sprite desktop-iconBag sprites-headerBag']"
add_items_from_wishlist = "//div[contains(@class,'button-base-button emptyCart-base-wishlistButton')]"
men_button = "//a[@class='desktop-main'][normalize-space()='Men']"
men_page_text = "//strong[contains(text(),'ONLINE SHOPPING FOR MEN: OPTIONS UNLIMITED ')]"
kids_option = "//a[@class='desktop-main'][normalize-space()='Kids']"
kids_text = "//strong[contains(text(),'MYNTRA FOR KIDS')]"
search_field = "//input[@placeholder='Search for products, brands and more']"
category_verify = "//li[@class='breadcrumbs-item'][position()=3]"
first_item = "//li[@class='product-base'][position()=1]"
item_verify = "//h1[@class='pdp-name']"
