"""
Locators related to men page
"""


men_button = "//a[@class='desktop-main'][normalize-space()='Men']"
men_page_text = "//strong[contains(text(),'ONLINE SHOPPING FOR MEN: OPTIONS UNLIMITED ')]"
search_field = "//input[@placeholder='Search for products, brands and more']"
items_selection = "//li[@class='product-base']"
first_item = "//li[@class='product-base'][position()=1]"
item_verify="//h1[@class='pdp-name']"
similar_products="//div[@class='similar-container']//li[@class='product-list-gist'][position()=1]"
similar_products_text = "//h3[@class='similar-heading']"
price="//span[@class='pdp-price']"
price_text="//span[@class='pdp-vatInfo']"
catagory_verify ="//li[@class='breadcrumbs-item'][position()=4]"
formal_shirts_option = "//a[contains(text(),'Formal Shirts')]"
kids_option = "//a[@class='desktop-main'][normalize-space()='Kids']"
kids_text = "//strong[contains(text(),'MYNTRA FOR KIDS')]"
pincode="//input[@type='tel']"
check_pincode="//button[@type='submit']"
check_pincode_text="//li[@class='pincode-serviceabilityItem'][position()=1]"
rating_text="//div[@id='headingContainer']"
average_rating = "//div[@class='index-flexRow index-averageRating']"
verified_users="//div[@class='index-countDesc']"