"""
Locators related to women page
"""


women_button = "//a[contains(text(),'Women')]"
women_text = "//strong[contains(text(),'ONLINE SHOPPING FOR WOMEN')]"
category_verify = "//h1[@class='title-title']"
search_field = "//input[@placeholder='Search for products, brands and more']"
items_selection = "//li[@class='product-base']"
ethnic_wear = "//a[@href='/women-ethnic-wear']"
kids_option = "//a[@class='desktop-main'][normalize-space()='Kids']"
kids_text = "//strong[contains(text(),'MYNTRA FOR KIDS')]"
first_item = "//li[@class='product-base'][position()=1]"
item_verify = "//h1[@class='pdp-name']"
pincode = "//input[@type='tel']"
check_pincode = "//button[@type='submit']"
check_pincode_text = "//li[@class='pincode-serviceabilityItem'][position()=1]"
average_rating = "//div[@class='index-flexRow index-averageRating']"
rating_text = "//div[@id='headingContainer']"
verified_users = "//div[@class='index-countDesc']"
similar_products = "//div[@class='similar-container']//li[@class='product-list-gist'][position()=1]"
similar_products_text = "//h3[@class='similar-heading']"
price = "//span[@class='pdp-price']"
price_text = "//span[@class='pdp-vatInfo']"
